[tool.ruff]
# Enable pycodestyle ('E'), pyflakes ('F'), isort ('I'), and black ('B') rules
lint.select = ["E", "F", "I", "B", "W", "C90"]
# Same as Black
line-length = 88
# Assume Python 3.10
target-version = "py310"
# Enable auto-fixes
fix = true

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"
# Enable preview features
preview = true

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.ruff.lint.mccabe]
max-complexity = 10 